spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticketone
    jdbcUrl: jdbc:postgresql://localhost:5432/ticketone
    username: postgres
    password: 1234


springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs